version: '3.1'

services:
  db:
    container_name: planshboard_postgres
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: grudus
      POSTGRES_PASSWORD: grudus
      POSTGRES_MULTIPLE_DATABASES: planshboard,planshboard_test

    ports:
      - 5432:5432
