package com.grudus.planshboard.commons

object RestKeys {
    const val EMPTY_USERNAME = "USERNAME.EMPTY"
    const val EMPTY_PASSWORD = "PASSWORD.EMPTY"
    const val USERNAME_EXISTS = "USERNAME.EXISTS"
    const val UNKNOWN_ERROR = "INTERNAL_SERVER_ERROR"
    const val PARAMETER_NOT_RESENT = "PARAMETER.NOT_PRESENT"
    const val DUPLICATES_FOUND = "PARAMETER.DUPLICATE"
    const val EMPTY_NAME = "NAME.EMPTY"
    const val NAME_EXISTS = "NAME.EXISTS"
    const val ELEMENT_NOT_FOUND = "ELEMENT.NOT_FOUND"
    const val NO_RESULTS: String = "RESULTS.EMPTY"
    const val BOARD_GAME_NOT_EXISTS: String = "BOARD_GAME.NOT_EXISTS"
    const val OPPONENTS_NOT_EXISTS: String = "OPPONENTS.NOT_EXIST"
    const val OPPONENTS_EXISTS: String = "OPPONENTS.EXISTS"
    const val DUPLICATED_OPPONENTS = "OPPONENTS.DUPLICATED"
    const val USER_NOT_EXIST = "USER.NOT_EXIST"
    const val USER_ASSIGNED_TO_ANOTHER_OPPONENT = "USER.ASSIGNED_TO_ANOTHER_OPPONENT"
}
