package com.grudus.planshboard.commons

object RestKeys {
    val EMPTY_USERNAME = "USERNAME.EMPTY"
    val EMPTY_PASSWORD = "PASSWORD.EMPTY"
    val USERNAME_EXISTS = "USERNAME.EXISTS"
    val UNKNOWN_ERROR = "INTERNAL_SERVER_ERROR"
    val PARAMETER_NOT_RESENT = "PARAMETER.NOT_PRESENT"
    val DUPLICATES_FOUND = "PARAMETER.DUPLICATE"
    val EMPTY_NAME = "NAME.EMPTY"
    val NAME_EXISTS = "NAME.EXISTS"
}