CREATE TABLE IF NOT EXISTS opponents (
  id      BIGSERIAL PRIMARY KEY,
  user_id BIGINT       NOT NULL REFERENCES users ON DELETE CASCADE,
  name    VARCHAR(255) NOT NULL,
  CONSTRAINT UNIQUE_OPPONENT_NAME UNIQUE (name, user_id)
);