CREATE TABLE IF NOT EXISTS plays (
  id           BIGSERIAL PRIMARY KEY,
  boardgame_id BIGINT NOT NULL REFERENCES boardgames ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS plays_results (
  id          BIGSERIAL PRIMARY KEY,
  opponent_id BIGINT NOT NULL REFERENCES opponents ON DELETE CASCADE,
  play_id     BIGINT NOT NULL REFERENCES plays ON DELETE CASCADE,
  points      INT    NULL
);