CREATE TABLE IF NOT EXISTS games (
  id           BIGSERIAL PRIMARY KEY,
  boardgame_id BIGINT NOT NULL REFERENCES boardgames ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS game_results (
  id          BIGSERIAL PRIMARY KEY,
  opponent_id BIGINT NOT NULL REFERENCES opponents ON DELETE CASCADE,
  game_id     BIGINT NOT NULL REFERENCES games ON DELETE CASCADE,
  points      INT    NULL
);